# Generated by Django 4.2.7 on 2023-11-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='kategoriid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berita',
            name='status',
            field=models.CharField(blank=True, choices=[('publish', 'publish'), ('draft', 'draft')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('viewers', 'viewers'), ('admin', 'admin')], default='admin', max_length=255, null=True),
        ),
    ]
