# Generated by Django 4.2.7 on 2023-11-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('viewers', 'viewers'), ('admin', 'admin')], default='admin', max_length=255, null=True),
        ),
    ]
