# Generated by Django 4.2.7 on 2023-11-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_berita_kategoriid_berita_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('viewers', 'viewers')], default='admin', max_length=255, null=True),
        ),
    ]
